stages:
  build:
    nodeLabel: sbt
    steps:
      - |
        sbt \
          clean \
          stack/clean \
          stack/test
    filesToStash:
      - '**'
  deployProd:
    nodeLabel: sbt-deployer
    steps:
      - |
        sbt \
          -DAWS_ACCOUNT_ID=455620323323 \
          publish \
          stack/deploy
